import "./globals.css";
import type { Metadata } from "next";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import { Provider } from "./provider";
import TopbarContainer from "@/components/topbar/topbar";
import Sidebar from "@/views/divers/sidebar";

export const metadata: Metadata = {
  title: "Scholar management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={`text-base font-medium bg-custom-secondary-white`}>
        <Provider>
          <div className="flex flex-row gap-1">
            <div className="sticky top-0 left-0 h-screen overflow-y-hidden">
              <Sidebar />
            </div>
            <main className="sticky top-0 flex flex-col gap-4 bg-custom-primary-white min-w-[1600px]  shadow-gray-600/50 z-10">
              <TopbarContainer />
              <section className="flex flex-col flex-grow relative px-12">
                {children}
              </section>
            </main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
